name: wakelock_example
description: Demonstrates how to use the wakelock plugin and is used for integration testing.
publish_to: 'none'

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  wakelock:
    path: ../

  flutter_driver:
    sdk: flutter
  test: # This is equivalent to any.
