name: wakelock_windows
description: >-2
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.2.2
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_windows

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  wakelock_platform_interface: ^0.3.0
  # win32 is compatible across v4 and v5 for Win32 only (not COM)
  win32: ">=4.0.0 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
