name: wakelock_windows
description: >-2
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.2.2
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_windows

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  wakelock_platform_interface: ^0.3.0
  win32: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
