// Autogenerated from Pigeon (v0.1.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTToggleMessage;
@class FLTIsEnabledMessage;

@interface FLTToggleMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * enable;
@end

@interface FLTIsEnabledMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * enabled;
@end

@protocol FLTWakelockApi
-(void)toggle:(FLTToggleMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable FLTIsEnabledMessage *)isEnabled:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTWakelockApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTWakelockApi> _Nullable api);

NS_ASSUME_NONNULL_END
