// Autogenerated from Pigeon (v0.1.14), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import
import 'dart:async';
import 'dart:typed_data' show Uint8List, Int32List, Int64List, Float64List;

import 'package:flutter/services.dart';

class ToggleMessage {
  late bool enable;

  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final pigeonMap = <dynamic, dynamic>{};
    pigeonMap['enable'] = enable;
    return pigeonMap;
  }

  // ignore: unused_element
  static ToggleMessage _fromMap(Map<dynamic, dynamic> pigeonMap) {
    final result = ToggleMessage();
    result.enable = pigeonMap['enable'];
    return result;
  }
}

class IsEnabledMessage {
  late bool enabled;

  // ignore: unused_element
  Map<dynamic, dynamic> _toMap() {
    final pigeonMap = <dynamic, dynamic>{};
    pigeonMap['enabled'] = enabled;
    return pigeonMap;
  }

  // ignore: unused_element
  static IsEnabledMessage _fromMap(Map<dynamic, dynamic> pigeonMap) {
    final result = IsEnabledMessage();
    result.enabled = pigeonMap['enabled'];
    return result;
  }
}

class WakelockApi {
  Future<void> toggle(ToggleMessage arg) async {
    final requestMap = arg._toMap();
    const channel = BasicMessageChannel<dynamic>(
        'dev.flutter.pigeon.WakelockApi.toggle', StandardMessageCodec());

    final replyMap = await channel.send(requestMap);
    if (replyMap == null) {
      throw PlatformException(
          code: 'channel-error',
          message: 'Unable to establish connection on channel.',
          details: null);
    } else if (replyMap['error'] != null) {
      final error = replyMap['error'];
      throw PlatformException(
          code: error['code'],
          message: error['message'],
          details: error['details']);
    } else {
      // noop
    }
  }

  Future<IsEnabledMessage> isEnabled() async {
    const channel = BasicMessageChannel<dynamic>(
        'dev.flutter.pigeon.WakelockApi.isEnabled', StandardMessageCodec());

    final replyMap = await channel.send(null);
    if (replyMap == null) {
      throw PlatformException(
          code: 'channel-error',
          message: 'Unable to establish connection on channel.',
          details: null);
    } else if (replyMap['error'] != null) {
      final error = replyMap['error'];
      throw PlatformException(
          code: error['code'],
          message: error['message'],
          details: error['details']);
    } else {
      return IsEnabledMessage._fromMap(replyMap['result']);
    }
  }
}

abstract class TestWakelockApi {
  void toggle(ToggleMessage arg);

  IsEnabledMessage isEnabled();

  static void setup(TestWakelockApi? api) {
    {
      const channel = BasicMessageChannel<dynamic>(
          'dev.flutter.pigeon.WakelockApi.toggle', StandardMessageCodec());
      if (api == null) {
        channel.setMockMessageHandler(null);
      } else {
        channel.setMockMessageHandler((dynamic message) async {
          final mapMessage = message as Map<dynamic, dynamic>;
          final input = ToggleMessage._fromMap(mapMessage);
          api.toggle(input);
          return <dynamic, dynamic>{};
        });
      }
    }
    {
      const channel = BasicMessageChannel<dynamic>(
          'dev.flutter.pigeon.WakelockApi.isEnabled', StandardMessageCodec());
      if (api == null) {
        channel.setMockMessageHandler(null);
      } else {
        channel.setMockMessageHandler((dynamic message) async {
          final output = api.isEnabled();
          return <dynamic, dynamic>{'result': output._toMap()};
        });
      }
    }
  }
}
