name: Pana

on:
  pull_request:
    branches:
      - master
    paths:
      - '**/lib/**'
      - '**/android/**'
      - '**/ios/**'
      - '**/pubspec.yaml'
      - '**/test/**'
      - '**/test_driver/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/dart-package-analyzer@v2.0.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
